CREATE TABLE IF NOT EXISTS Users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(200) ,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Items(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250),
    description VARCHAR,
    is_available BOOLEAN,
    owner_id INTEGER,
    request_id INTEGER,
    FOREIGN KEY (owner_id) REFERENCES Users(id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Bookings(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    item_id INTEGER,
    booker_id INTEGER,
    status VARCHAR(20),
    FOREIGN KEY (item_id) REFERENCES Items(id),
    FOREIGN KEY (booker_id) REFERENCES Users(id),
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT end_after_start CHECK (end>start)
);

CREATE TABLE IF NOT EXISTS Requests(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR,
    requestor_id INTEGER,
    FOREIGN KEY (requestor_id) REFERENCES Users(id),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Comments(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    item_id INTEGER,
    author_id INTEGER,
    FOREIGN KEY (item_id) REFERENCES Items(id),
    FOREIGN KEY (author_id) REFERENCES Users(id),
    CONSTRAINT pk_comment PRIMARY KEY (id)
);